### PR TITLE
add pthread for linker

### PR DESCRIPTION
**Pull request by floriantschopp**

### CODE REVIEW

**Comment by LBern** [comment]
I'm surprised that you don't do `-lpthread`, to only link against the libraries. Do we need the preprocessor flags? 
The only thing that I wanna put into discussion is that `-pthread` is also platform specific (AFAIK).

**Comment by floriantschopp** [comment]
Only adding -lpthread doesn't work for me.

**Comment by mfehr** [comment]
have you tried adding pthread to target_link_libraries ? I think that's what we do in other packages as well?

**Comment by floriantschopp** [comment]
@mfehr That seems to work, thank you!

**Pull request merged**
